// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "./S.bs.js";
import * as Core from "./Core.bs.js";
import * as React from "react";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.mjs";
import * as ReactNative from "react-native";

function useCardStyle(p, m, param) {
  return S.make({
              hd: S.backgroundColor("bodyUp1"),
              tl: {
                hd: S.flexWrap("wrap"),
                tl: {
                  hd: S.flexDirection("column"),
                  tl: {
                    hd: S.alignItems("stretch"),
                    tl: {
                      hd: S.borderRadius("large"),
                      tl: {
                        hd: S.borderWidth(1),
                        tl: {
                          hd: S.borderColor({
                                NAME: "highlight",
                                VAL: [
                                  8,
                                  "body"
                                ]
                              }),
                          tl: {
                            hd: S.borderStyle("solid"),
                            tl: {
                              hd: S.margin(m),
                              tl: {
                                hd: S.padding(p),
                                tl: {
                                  hd: S.shadowOffset([
                                        0,
                                        4
                                      ]),
                                  tl: {
                                    hd: S.shadowColor({
                                          NAME: "unsafeCustomColor",
                                          VAL: {
                                            NAME: "lab",
                                            VAL: [
                                              0,
                                              0,
                                              0,
                                              1
                                            ]
                                          }
                                        }),
                                    tl: {
                                      hd: S.shadowOpacity(Core.Styles.getIsLight(undefined) ? 0.05 : 0.35),
                                      tl: {
                                        hd: S.shadowRadius(5),
                                        tl: /* [] */0
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            });
}

function Card(Props) {
  var style_ = Props.style;
  var $staropt$star = Props.grow;
  var $staropt$star$1 = Props.padding;
  var margin = Props.margin;
  var children = Props.children;
  $staropt$star !== undefined;
  var padding = $staropt$star$1 !== undefined ? $staropt$star$1 : "single";
  var $$default = useCardStyle(padding, margin, undefined);
  var style = Belt_Option.mapWithDefault(style_, $$default, (function (param) {
          return S.merge($$default, param);
        }));
  return React.createElement(ReactNative.View, {
              style: style,
              children: children
            });
}

var make = Card;

export {
  useCardStyle ,
  make ,
  
}
/* S Not a pure module */
