// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as S from "./S.bs.js";
import * as Core from "./Core.bs.js";
import * as React from "react";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as ReactNative from "react-native";

function useCardStyle(p, m, param) {
  return S.make({
              hd: S.backgroundColor(/* bodyUp1 */824326132),
              tl: {
                hd: S.flexWrap(/* wrap */-822134326),
                tl: {
                  hd: S.flexDirection(/* column */-963948842),
                  tl: {
                    hd: S.alignItems(/* stretch */-162316795),
                    tl: {
                      hd: S.borderRadius(/* large */-272944197),
                      tl: {
                        hd: S.borderWidth(1),
                        tl: {
                          hd: S.borderColor({
                                HASH: /* highlight */-318745036,
                                VAL: [
                                  8,
                                  /* body */-1055163742
                                ]
                              }),
                          tl: {
                            hd: S.borderStyle(/* solid */12956715),
                            tl: {
                              hd: S.margin(m),
                              tl: {
                                hd: S.padding(p),
                                tl: {
                                  hd: S.shadowOffset([
                                        0,
                                        4
                                      ]),
                                  tl: {
                                    hd: S.shadowColor({
                                          HASH: /* unsafeCustomColor */534360428,
                                          VAL: {
                                            HASH: /* lab */5392461,
                                            VAL: [
                                              0,
                                              0,
                                              0,
                                              1
                                            ]
                                          }
                                        }),
                                    tl: {
                                      hd: S.shadowOpacity(Core.Styles.getIsLight(undefined) ? 0.05 : 0.35),
                                      tl: {
                                        hd: S.shadowRadius(5),
                                        tl: /* [] */0
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            });
}

function Card(Props) {
  var style_ = Props.style;
  Props.grow;
  var paddingOpt = Props.padding;
  var margin = Props.margin;
  var children = Props.children;
  var padding = paddingOpt !== undefined ? paddingOpt : /* single */958490248;
  var $$default = useCardStyle(padding, margin, undefined);
  var style = Belt_Option.mapWithDefault(style_, $$default, (function (param) {
          return S.merge($$default, param);
        }));
  return React.createElement(ReactNative.View, {
              style: style,
              children: children
            });
}

var make = Card;

export {
  useCardStyle ,
  make ,
  
}
/* S Not a pure module */
