// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$Text from "./Text.bs.js";
import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function Heading(Props) {
  var levelOpt = Props.level;
  var style = Props.style;
  var colorOpt = Props.color;
  Props.margin;
  var children = Props.children;
  var level = levelOpt !== undefined ? levelOpt : /* h1 */23241;
  var color = colorOpt !== undefined ? colorOpt : /* body */-1055163742;
  var match = level !== 23242 ? (
      level >= 23244 ? (
          level >= 23245 ? [
              1,
              /* bold */-1055161979
            ] : [
              2,
              /* bold */-1055161979
            ]
        ) : (
          level >= 23243 ? [
              3,
              /* bold */-1055161979
            ] : [
              5,
              /* bold */-1055161979
            ]
        )
    ) : [
      4,
      /* bold */-1055161979
    ];
  var tmp = {
    weight: match[1],
    color: color,
    size: match[0],
    children: children
  };
  if (style !== undefined) {
    tmp.style = Caml_option.valFromOption(style);
  }
  return React.createElement($$Text.make, tmp);
}

var make = Heading;

export {
  make ,
  
}
/* Text Not a pure module */
