// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as S from "./S.bs.js";
import * as List from "bs-platform/lib/es6/list.js";
import * as React from "react";
import * as StackMap from "./StackMap";
import * as ReactNative from "react-native";

function childMap(prim, prim$1) {
  return StackMap.stackMap(prim, prim$1);
}

function base(direction, align, param) {
  return S.make(List.append({
                  hd: S.flexShrink(1),
                  tl: {
                    hd: S.justifyContent(/* flexStart */662439529),
                    tl: {
                      hd: S.alignItems(align),
                      tl: {
                        hd: S.alignContent(/* flexStart */662439529),
                        tl: /* [] */0
                      }
                    }
                  }
                }, direction >= 5693978 ? ({
                      hd: S.flexDirection(/* row */5693978),
                      tl: /* [] */0
                    }) : /* [] */0));
}

function make(margin, direction, param) {
  return S.make(List.append({
                  hd: S.flexShrink(0),
                  tl: {
                    hd: S.flexGrow(0),
                    tl: {
                      hd: S.flexBasis({
                            HASH: /* pct */5591841,
                            VAL: 100
                          }),
                      tl: /* [] */0
                    }
                  }
                }, direction >= 5693978 ? ({
                      hd: S.flexDirection(/* row */5693978),
                      tl: {
                        hd: S.marginRight(margin),
                        tl: /* [] */0
                      }
                    }) : ({
                      hd: S.marginBottom(margin),
                      tl: /* [] */0
                    })));
}

var Styles = {
  base: base,
  make: make
};

function Stack(Props) {
  var mOpt = Props.margin;
  var directionOpt = Props.direction;
  var alignOpt = Props.align;
  var children = Props.children;
  var m = mOpt !== undefined ? mOpt : /* double */852175633;
  var direction = directionOpt !== undefined ? directionOpt : /* column */-963948842;
  var align = alignOpt !== undefined ? alignOpt : /* center */98248149;
  return React.createElement(ReactNative.View, {
              style: base(direction, align, undefined),
              children: StackMap.stackMap((function (child, last) {
                      if (last) {
                        return child;
                      } else {
                        return React.createElement(React.Fragment, undefined, child, React.createElement(ReactNative.View, {
                                        style: S.make({
                                              hd: S.paddingLeft(m),
                                              tl: {
                                                hd: S.alignSelf(/* stretch */-162316795),
                                                tl: /* [] */0
                                              }
                                            }),
                                        children: null
                                      }));
                      }
                    }), children)
            });
}

var make$1 = Stack;

export {
  childMap ,
  Styles ,
  make$1 as make,
  
}
/* S Not a pure module */
