// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Box from "./Box.bs.js";
import * as Core from "./Core.bs.js";
import * as View from "./View.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.mjs";
import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.mjs";
import * as ReactNative from "react-native";

function TouchableOpacity(Props) {
  var $staropt$star = Props.style;
  var $staropt$star$1 = Props.position;
  var $staropt$star$2 = Props.align;
  var $staropt$star$3 = Props.alignSelf;
  var $staropt$star$4 = Props.alignContent;
  var $staropt$star$5 = Props.backgroundColor;
  var $staropt$star$6 = Props.grow;
  var $staropt$star$7 = Props.wrap;
  var $staropt$star$8 = Props.shrink;
  var $staropt$star$9 = Props.justify;
  var $staropt$star$10 = Props.direction;
  var $staropt$star$11 = Props.onlyFocusOnTab;
  var padding = Props.padding;
  var margin = Props.margin;
  var $staropt$star$12 = Props.basis;
  var $staropt$star$13 = Props.height;
  var $staropt$star$14 = Props.width;
  var $staropt$star$15 = Props.maxWidth;
  var $staropt$star$16 = Props.overflow;
  var $staropt$star$17 = Props.borderRadius;
  var onPress = Props.onPress;
  var children = Props.children;
  $staropt$star !== undefined;
  var position = $staropt$star$1 !== undefined ? $staropt$star$1 : "relative";
  var align = $staropt$star$2 !== undefined ? $staropt$star$2 : "flexStart";
  var alignSelf = $staropt$star$3 !== undefined ? $staropt$star$3 : "auto";
  var alignContent = $staropt$star$4 !== undefined ? $staropt$star$4 : "flexStart";
  var backgroundColor = $staropt$star$5 !== undefined ? $staropt$star$5 : "transparent";
  var grow = $staropt$star$6 !== undefined ? $staropt$star$6 : 1;
  var wrap = $staropt$star$7 !== undefined ? $staropt$star$7 : "wrap";
  var shrink = $staropt$star$8 !== undefined ? $staropt$star$8 : 0;
  var justify = $staropt$star$9 !== undefined ? $staropt$star$9 : "flexStart";
  var direction = $staropt$star$10 !== undefined ? $staropt$star$10 : "column";
  if ($staropt$star$11 === undefined) {
    true;
  }
  var basis = $staropt$star$12 !== undefined ? $staropt$star$12 : "auto";
  var height = $staropt$star$13 !== undefined ? $staropt$star$13 : "auto";
  var width = $staropt$star$14 !== undefined ? $staropt$star$14 : "auto";
  var maxWidth = $staropt$star$15 !== undefined ? $staropt$star$15 : "auto";
  var overflow = $staropt$star$16 !== undefined ? $staropt$star$16 : "scroll";
  var borderRadius = $staropt$star$17 !== undefined ? $staropt$star$17 : "none";
  var style = Box.getBoxStyle(position, align, alignSelf, alignContent, backgroundColor, grow, basis, wrap, shrink, justify, direction, padding, margin, height, width, maxWidth, overflow, borderRadius, undefined);
  var tmp = {
    children: React.createElement(View.make, {
          style: style,
          children: children
        })
  };
  var tmp$1 = onPress !== undefined ? Curry.__1(onPress) : undefined;
  if (tmp$1 !== undefined) {
    tmp.onPress = Caml_option.valFromOption(tmp$1);
  }
  return React.createElement(Core.BackgroundColorContext.Provider.make, {
              value: backgroundColor,
              children: React.createElement(ReactNative.TouchableOpacity, tmp)
            });
}

var make = TouchableOpacity;

export {
  make ,
  
}
/* Box Not a pure module */
