// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";

function UnsafeCreateReactElement(Props) {
  var tagOpt = Props.tag;
  var props = Props.props;
  var tag = tagOpt !== undefined ? tagOpt : ReactNative.View;
  return React.createElement(tag, props);
}

function create(tag, props) {
  return React.createElement(tag, props);
}

var make = UnsafeCreateReactElement;

export {
  make ,
  create ,
  
}
/* react Not a pure module */
