// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as S from "./revy/S.bs.js";
import * as Lab from "./revy/Lab.bs.js";
import * as Core from "./revy/Core.bs.js";
import * as React from "react";
import * as Editor from "./Editor.bs.js";
import * as ReactNative from "react-native";

Core.setTheme(Core.createTheme(1.25, 14, 60, 4, {
          small: 2,
          medium: 4,
          large: 6
        }, {
          body: {
            hd: "System",
            tl: /* [] */0
          },
          title: {
            hd: "System",
            tl: /* [] */0
          },
          mono: {
            hd: "Menlo",
            tl: /* [] */0
          },
          alt: {
            hd: "System",
            tl: /* [] */0
          }
        }, {
          neutral: Lab.fromRGB({
                HASH: /* rgb */5692173,
                VAL: [
                  40,
                  40,
                  40
                ]
              }),
          primary: Lab.fromRGB({
                HASH: /* rgb */5692173,
                VAL: [
                  18,
                  120,
                  240
                ]
              }),
          secondary: Lab.fromRGB({
                HASH: /* rgb */5692173,
                VAL: [
                  100,
                  100,
                  100
                ]
              }),
          success: Lab.fromRGB({
                HASH: /* rgb */5692173,
                VAL: [
                  44,
                  173,
                  2
                ]
              }),
          warning: Lab.fromRGB({
                HASH: /* rgb */5692173,
                VAL: [
                  214,
                  135,
                  5
                ]
              }),
          error: Lab.fromRGB({
                HASH: /* rgb */5692173,
                VAL: [
                  230,
                  26,
                  26
                ]
              }),
          brand1: Lab.fromRGB({
                HASH: /* rgb */5692173,
                VAL: [
                  213,
                  54,
                  222
                ]
              }),
          brand2: Lab.fromRGB({
                HASH: /* rgb */5692173,
                VAL: [
                  54,
                  213,
                  222
                ]
              }),
          body: {
            HASH: /* lab */5392461,
            VAL: [
              1,
              0,
              0,
              1
            ]
          },
          bodyDown1: {
            HASH: /* lab */5392461,
            VAL: [
              2,
              0,
              0,
              1
            ]
          },
          bodyDown2: {
            HASH: /* lab */5392461,
            VAL: [
              1,
              0,
              0,
              1
            ]
          },
          bodyDown3: {
            HASH: /* lab */5392461,
            VAL: [
              0,
              0,
              0,
              1
            ]
          },
          bodyUp1: {
            HASH: /* lab */5392461,
            VAL: [
              15,
              0,
              0,
              1
            ]
          },
          bodyUp2: {
            HASH: /* lab */5392461,
            VAL: [
              20,
              0,
              0,
              1
            ]
          },
          bodyUp3: {
            HASH: /* lab */5392461,
            VAL: [
              25,
              0,
              0,
              1
            ]
          },
          bodyText: {
            HASH: /* lab */5392461,
            VAL: [
              80,
              0,
              0,
              1
            ]
          },
          quiet: Lab.fromRGB({
                HASH: /* rgb */5692173,
                VAL: [
                  130,
                  130,
                  130
                ]
              })
        }, 700, undefined));

var style = S.make({
      hd: S.backgroundColor(/* body */-1055163742),
      tl: {
        hd: S.width({
              HASH: /* pct */5591841,
              VAL: 100
            }),
        tl: {
          hd: S.flex(1),
          tl: {
            hd: S.flexGrow(1),
            tl: {
              hd: S.padding(/* double */852175633),
              tl: /* [] */0
            }
          }
        }
      }
    });

function App(Props) {
  return React.createElement(ReactNative.View, {
              style: style,
              children: React.createElement(Editor.make, {})
            });
}

var make = App;

export {
  style ,
  make ,
  
}
/*  Not a pure module */
