// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as List$Credt from "credt/library/List.bs.js";

function Make(Config) {
  var InternalList = List$Credt.Make(Config);
  var use = function (param) {
    var match = React.useReducer((function (c, param) {
            return c + 1 | 0;
          }), 0);
    var forceUpdate = match[1];
    var valRef = React.useRef(Curry._1(InternalList.instance.getSnapshot, undefined));
    React.useEffect((function () {
            var listener = function (v) {
              valRef.current = Curry._1(InternalList.instance.getSnapshot, undefined);
              return Curry._1(forceUpdate, undefined);
            };
            Curry._1(InternalList.instance.addChangeListener, listener);
            return (function (param) {
                      return Curry._1(InternalList.removeChangeListener, listener);
                    });
          }), []);
    return valRef.current;
  };
  return {
          InternalList: InternalList,
          use: use
        };
}

export {
  Make ,
  
}
/* react Not a pure module */
