// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.mjs";
import * as React from "react";
import * as Belt_MapString from "bs-platform/lib/es6/belt_MapString.mjs";

function Make(Config) {
  var context = React.createContext(Curry._1(Config.instance.getSnapshot, undefined));
  var makeProps = function (value, children, param) {
    return {
            value: value,
            children: children
          };
  };
  var make = context.Provider;
  var Provider_ = {
    makeProps: makeProps,
    make: make
  };
  var CredtMapContext$Make$Provider = function (Props) {
    var children = Props.children;
    var partial_arg = Config.instance.getSnapshot;
    var match = React.useState(function () {
          return Curry._1(partial_arg, undefined);
        });
    var setValue = match[1];
    React.useEffect((function () {
            var listener = function (param) {
              return Curry._1(setValue, (function (param) {
                            return Curry._1(Config.instance.getSnapshot, undefined);
                          }));
            };
            Curry._1(Config.instance.addChangeListener, listener);
            return (function (param) {
                      return Curry._1(Config.instance.removeChangeListener, listener);
                    });
          }), []);
    return React.createElement(make, makeProps(match[0], children, undefined));
  };
  var Provider = {
    make: CredtMapContext$Make$Provider
  };
  var useById = function (id) {
    return Belt_MapString.get(React.useContext(context), id);
  };
  return {
          context: context,
          Provider_: Provider_,
          Provider: Provider,
          useById: useById
        };
}

export {
  Make ,
  
}
/* react Not a pure module */
