// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as DateFns from "date-fns";
import * as Locale from "date-fns/locale";

function format(date, string) {
  return DateFns.format(date, string, {
              locale: Locale.sv
            });
}

export {
  format ,
  
}
/* date-fns Not a pure module */
