// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DateFns from "date-fns";
import * as DateFnsTz from "date-fns-tz";
import * as Locale from "date-fns/locale";

function format(date, string) {
  return DateFns.format(date, string, {
              locale: Locale.sv
            });
}

function utcToZonedTime(d) {
  return DateFnsTz.utcToZonedTime(d, {
              locale: Locale.sv
            });
}

function zonedTimeToUtc(d) {
  return DateFnsTz.zonedTimeToUtc(d, {
              locale: Locale.sv
            });
}

function startOfMonth(d) {
  var d$1 = DateFns.startOfMonth(d);
  return DateFnsTz.zonedTimeToUtc(d$1, {
              locale: Locale.sv
            });
}

function startOfYear(d) {
  var d$1 = DateFns.startOfYear(d);
  return DateFnsTz.zonedTimeToUtc(d$1, {
              locale: Locale.sv
            });
}

function endOfMonth(d) {
  var d$1 = DateFns.endOfMonth(d);
  return DateFnsTz.zonedTimeToUtc(d$1, {
              locale: Locale.sv
            });
}

function startOfWeek(date) {
  var d = DateFns.startOfWeek(date, {
        locale: Locale.sv
      });
  return DateFnsTz.zonedTimeToUtc(d, {
              locale: Locale.sv
            });
}

function endOfWeek(date) {
  var d = DateFns.endOfWeek(date, {
        locale: Locale.sv
      });
  return DateFnsTz.zonedTimeToUtc(d, {
              locale: Locale.sv
            });
}

function now(param) {
  return new Date(Date.now());
}

export {
  format ,
  utcToZonedTime ,
  zonedTimeToUtc ,
  startOfMonth ,
  startOfYear ,
  endOfMonth ,
  startOfWeek ,
  endOfWeek ,
  now ,
  
}
/* date-fns Not a pure module */
