// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Array from "rescript/lib/es6/array.js";
import * as React from "react";

function useInterval(delay, callback, deps) {
  var savedCallback = React.useRef(callback);
  React.useEffect((function () {
          savedCallback.current = callback;
          
        }), [callback]);
  React.useEffect((function () {
          var handler = savedCallback.current;
          var id = setInterval(handler, delay);
          return (function (param) {
                    clearInterval(id);
                    
                  });
        }), $$Array.concat({
            hd: [delay],
            tl: {
              hd: deps,
              tl: /* [] */0
            }
          }));
  
}

export {
  useInterval ,
  
}
/* react Not a pure module */
