// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "./revy/S.bs.js";
import * as Box from "./revy/Box.bs.js";
import * as $$Text from "./revy/Text.bs.js";
import * as React from "react";
import * as Spacer from "./revy/Spacer.bs.js";
import * as $$String from "bs-platform/lib/es6/string.mjs";
import * as DateFns from "./DateFns.bs.js";
import * as DateFns$1 from "date-fns";
import * as DiaryHooks from "./DiaryHooks.bs.js";
import * as ReactNative from "react-native";

function Reader(Props) {
  var date = Props.date;
  var match = DiaryHooks.useDiaryText(date);
  return React.createElement(ReactNative.View, {
              style: S.make({
                    hd: S.flexGrow(1),
                    tl: /* [] */0
                  }),
              children: React.createElement(Box.make, {
                    align: "center",
                    alignContent: "center",
                    grow: 1,
                    padding: "half",
                    height: {
                      NAME: "pct",
                      VAL: 100
                    },
                    children: React.createElement(Box.make, {
                          grow: 1,
                          width: {
                            NAME: "px",
                            VAL: 621
                          },
                          maxWidth: {
                            NAME: "pct",
                            VAL: 100
                          },
                          overflow: "visible",
                          children: null
                        }, React.createElement(Box.make, {
                              alignSelf: "flexStart",
                              grow: 0,
                              direction: "row",
                              children: React.createElement($$Text.make, {
                                    weight: "_700",
                                    size: 4,
                                    children: $$String.capitalize_ascii(DateFns.format(date, "eeee dd LLLL" + (
                                              DateFns$1.isSameYear(date, new Date(Date.now())) ? "" : " yyyy"
                                            )))
                                  })
                            }), React.createElement(Spacer.make, {}), React.createElement(ReactNative.ScrollView, {
                              contentContainerStyle: S.make({
                                    hd: S.width({
                                          NAME: "pct",
                                          VAL: 100
                                        }),
                                    tl: {
                                      hd: S.alignContent("stretch"),
                                      tl: {
                                        hd: S.justifyContent("flexStart"),
                                        tl: {
                                          hd: S.alignItems("stretch"),
                                          tl: {
                                            hd: S.flexGrow(1),
                                            tl: /* [] */0
                                          }
                                        }
                                      }
                                    }
                                  }),
                              style: S.make({
                                    hd: S.width({
                                          NAME: "pct",
                                          VAL: 100
                                        }),
                                    tl: {
                                      hd: S.flexGrow(1),
                                      tl: /* [] */0
                                    }
                                  }),
                              children: React.createElement($$Text.make, {
                                    letterSpacing: 0.5,
                                    children: match[0]
                                  })
                            }))
                  })
            });
}

var make = Reader;

export {
  make ,
  
}
/* S Not a pure module */
