// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.mjs";

function throttle(fn, timeoutOpt) {
  var timeout = timeoutOpt !== undefined ? timeoutOpt : 1000;
  var throttling = {
    contents: false
  };
  return function (a) {
    if (!throttling.contents) {
      throttling.contents = true;
      Curry._1(fn, a);
      setTimeout((function (param) {
              throttling.contents = false;
              
            }), timeout);
      return ;
    }
    
  };
}

export {
  throttle ,
  
}
/* No side effect */
